import React, { useState } from "react";
import Select from "react-select";
import makeAnimated from "react-select/animated";

const animatedComponents = makeAnimated();

const SelectTrain = ({ onSelect }) => {
  const [selectedTrain, setSelectedTrain] = useState(null);
  const [selectedValue, setSelectedValue] = useState(null);

  const trainList = [
    { value: "CSTM", label: "CHHATRAPATI Shivaji Terminus" },
    { value: "KYN", label: "Kalyan" },
    { value: "PNVL", label: "Panvel" },
    { value: "NK", label: "Nasik road" },
    { value: "SUR", label: "Solapur" },
    { value: "MMR", label: "Manmad" },
    { value: "GR", label: "Gulbarga" },
    { value: "AK", label: "Akola" },
    { value: "JL", label: "Jalgaon" },
    { value: "MRJ", label: "Miraj" },
    { value: "SNSI", label: "Sainagar sirdih" },
    { value: "KOP", label: "Kolhapur" },
    { value: "BD", label: "Badnera" },
    { value: "KNW", label: "Khandawa" },
    { value: "KPG", label: "Kopargaon" },
    { value: "DD", label: "Daud" },
    { value: "ANG", label: "Ahmad nagar" },
    { value: "WR", label: "Wardha" },
    { value: "SEG", label: "Shegaon" },
    { value: "AMI", label: "Amrawati" },
    { value: "BPQ", label: "BALHARSHAH" },
    { value: "LNL", label: "Lonavala" },
    { value: "CD", label: "Chandrapur" },
    { value: "LUR", label: "Latur" },
    { value: "BZU", label: "Betul" },
    { value: "BAU", label: "Burhanpur" },
    { value: "KWV", label: "Kurduwadi" },
    { value: "CSN", label: "Chalisgaon" },
    { value: "MKU", label: "Malkapur" },
    { value: "SEGM", label: "Sewagram" },
    { value: "BIRD", label: "Bhiwandi Road" },
    { value: "WADI", label: "wadi" },
    { value: "DI", label: "Dombivali" },
    { value: "BUD", label: "Badalapur" },
    { value: "GC", label: "Ghatkopar" },
    { value: "CLA", label: "Kurla" },
    { value: "ABH", label: "Ambarnath" },
    { value: "MNKD", label: "Mankhurd" },
    { value: "MLND", label: "Mulund" },
    { value: "MBQ", label: "Mumbra" },
    { value: "BEPR", label: "Belapur" },
    { value: "TLA", label: "Titwala" },
    { value: "BND", label: "Bhandup" },
    { value: "NEU", label: "Nerul" },
    { value: "VSH", label: "Vashi" },
    { value: "KHAG", label: "Kharghar" },
    { value: "GV", label: "Govandi" },
    { value: "ULNR", label: "Ulhasnagar" },
    { value: "VK", label: "Vikhroli" },
    { value: "KLVA", label: "Kalwa" },
    { value: "BY", label: "Byculla" },
    { value: "SIN", label: "Sion" },
    { value: "AIRL", label: "Aeroli" },
    { value: "KJT", label: "Karjat" },
    { value: "CMBR", label: "Chembur" },
    { value: "GTBN", label: "Guru Teg bahadur nagar" },
    { value: "GNSL", label: "Ghansoli" },
    { value: "MANR", label: "Mansoravar" },
    { value: "SNCR", label: "Sanpada" },
    { value: "SDAH", label: "Sealdah" },
    { value: "KOAA", label: "Kolkatta terminal" },
    { value: "BGP", label: "Bhagalpur" },
    { value: "ASN", label: "Asansol" },
    { value: "BWN", label: "Barddhman" },
    { value: "NH", label: "Naihati" },
    { value: "MLDT", label: "Malda Town" },
    { value: "JSME", label: "Jasidih" },
    { value: "DGR", label: "Durgapur" },
    { value: "JMP", label: "Jamalpur" },
    { value: "RPH", label: "Rampurhat" },
    { value: "BDC", label: "Bandel Jn." },
    { value: "NFK", label: "New Farakka" },
    { value: "MDP", label: "Madhupur" },
    { value: "BHP", label: "Bolpur" },
    { value: "BPC", label: "Berhampur court" },
    { value: "SGG", label: "Sultanganj" },
    { value: "RNG", label: "Raniganj" },
    { value: "UDL", label: "Andal" },
    { value: "KNJ", label: "Krishnanagar city" },
    { value: "BP", label: "Barackpur" },
    { value: "SPR", label: "Srirampur" },
    { value: "DDJ", label: "Dum Dum Jn." },
    { value: "SEP", label: "Sodepur" },
    { value: "BRP", label: "Baruipur jn." },
    { value: "SRP", label: "Srirampur" },
    { value: "RIS", label: "Rishra" },
    { value: "KOG", label: "Konnagar" },
    { value: "BT", label: "Barasat jn." },
    { value: "BLH", label: "Belghoria" },
    { value: "SBGR", label: "Subhasgram" },
    { value: "SNR", label: "Shyamngar" },
    { value: "BNXR", label: "Bidhannagar" },
    { value: "HB", label: "Habra" },
    { value: "MMG", label: "Madhyamgram" },
    { value: "SHE", label: "Sheoraphuli" },
    { value: "RHA", label: "Ranaghat jn." },
    { value: "KDH", label: "Khardah" },
    { value: "CDH", label: "Chakdah" },
    { value: "PNBE", label: "Patna" },
    { value: "MFP", label: "Muzzafarpur" },
    { value: "MGS", label: "Mughalsarai" },
    { value: "GAYA", label: "Gaya" },
    { value: "DHN", label: "Dhanbad" },
    { value: "DBG", label: "Darbhanga" },
    { value: "RJPB", label: "Rajendra Nagar Terminal" },
    { value: "PPTA", label: "Patliputra" },
    { value: "SPJ", label: "Samastipur" },
    { value: "SHC", label: "Saharsa" },
    { value: "ARA", label: "Ara" },
    { value: "BXR", label: "Buxar" },
    { value: "DNR", label: "Danapur" },
    { value: "BJU", label: "Barauni Jn." },
    { value: "HJP", label: "Hajipur" },
    { value: "KQR", label: "Koderma" },
    { value: "BMKI", label: "Banmankhi" },
    { value: "DOS", label: "Dehri On Sone" },
    { value: "KIUL", label: "Kiul" },
    { value: "KGG", label: "Khagaria" },
    { value: "RXL", label: "Raxaul" },
    { value: "SSM", label: "Sasaram" },
    { value: "BTH", label: "Bettiah" },
    { value: "JYG", label: "Jainagar" },
    { value: "PNME", label: "Parasnath" },
    { value: "MBI", label: "Madhubani" },
    { value: "DTO", label: "Daltengunj" },
    { value: "BKP", label: "Bakhtiyarpur" },
    { value: "AUBR", label: "Anugrah Narayan Road" },
    { value: "SGL", label: "Sugauli" },
    { value: "NKE", label: "Narkatiaganj" },
    { value: "BGS", label: "Begusarai" },
    { value: "SKI", label: "Sakari Jn" },
    { value: "PNC", label: "Patna Sahib" },
    { value: "SMI", label: "Sitamadhi" },
    { value: "JMU", label: "Jamui" },
    { value: "MKA", label: "Mokama" },
    { value: "JAJ", label: "Jhanja" },
    { value: "SGRL", label: "Singrauli" },
    { value: "BBU", label: "Bhabhua Road" },
    { value: "GHD", label: "Garhwa Road" },
    { value: "MNE", label: "Mansi Jn." },
    { value: "DLN", label: "Dildarnagar" },
    { value: "BUG", label: "Bagha" },
    { value: "NNA", label: "Naugachia" },
    { value: "SEE", label: "Sonepur" },
    { value: "BRKA", label: "Barkakana" },
    { value: "JHD", label: "Jahanabad" },
    { value: "TEA", label: "Taregana" },
    { value: "FUT", label: "Fatuha" },
    { value: "BTA", label: "Bihta" },
    { value: "BARH", label: "Barh" },
    { value: "PURI", label: "Puri" },
    { value: "BAM", label: "Brahmapur" },
    { value: "CTC", label: "Cuttack" },
    { value: "VZM", label: "Viizanagaram" },
    { value: "SBP", label: "Sambalpur" },
    { value: "KUR", label: "Khurda Road" },
    { value: "CHE", label: "Srikakulam" },
    { value: "BHC", label: "Bhadrak" },
    { value: "PSA", label: "Palasa" },
    { value: "RGDA", label: "Rayagada" },
    { value: "JJKR", label: "Jajpur-Keonjhar road" },
    { value: "DVD", label: "Duvvada" },
    { value: "BLGR", label: "Bolangir" },
    { value: "TIG", label: "Titlagrah" },
    { value: "BALU", label: "Balugaon" },
    { value: "KSNG", label: "Kesinga" },
    { value: "DLI", label: "Delhi" },
    { value: "JAT", label: "Jammu Tavi" },
    { value: "BSB", label: "Varanasi" },
    { value: "LKO", label: "Lucknow" },
    { value: "LDH", label: "Ludhiana Jn" },
    { value: "HW", label: "Haridwar" },
    { value: "UMB", label: "Ambala Cantt." },
    { value: "SNP", label: "Sonipat" },
    { value: "BE", label: "Bareilly" },
    { value: "DDN", label: "Dehradun" },
    { value: "SVDK", label: "Shri Mata  Vaisno devi Katra" },
    { value: "MB", label: "Moradabad" },
    { value: "SRE", label: "Haharanpur" },
    { value: "FD", label: "Faizabad" },
    { value: "BTI", label: "Bathinda" },
    { value: "PTKC", label: "Pathankot Jn" },
    { value: "MTC", label: "Meerut City" },
    { value: "SLN", label: "Sultanpur" },
    { value: "JRC", label: "Jalandhar City" },
    { value: "SPN", label: "Shahjahanpur" },
    { value: "KLK", label: "Kalka" },
    { value: "PBH", label: "Pratapgrah" },
    { value: "SHG", label: "Shahgunj" },
    { value: "FZR", label: "Firozpur Cantt" },
    { value: "JNU", label: "Jaunpur" },
    { value: "ABP", label: "Akbarpur" },
    { value: "RBL", label: "Raebareli" },
    { value: "RK", label: "Roorkee" },
    { value: "ROK", label: "Rohtak" },
    { value: "HRI", label: "raichu" },
    { value: "MOZ", label: "Muzaffar Nagar" },
    { value: "PGW", label: "Phagwara Jn." },
    { value: "PWL", label: "Palwal" },
    { value: "RMU", label: "Rampur" },
    { value: "UHP", label: "Udhampur" },
    { value: "BOY", label: "Bhadohi" },
    { value: "RPJ", label: "Raj Pura" },
    { value: "JNH", label: "Janghai" },
    { value: "PRG", label: "Paryag" },
    { value: "PTK", label: "Pathan kot Jn" },
    { value: "HPU", label: "Hapur" },
    { value: "ON", label: "Unnao" },
    { value: "SIR", label: "Sirhind" },
    { value: "KKDE", label: "Kurukshetra" },
    { value: "BBK", label: "Barabanki" },
    { value: "JOP", label: "Jaunpur City" },
    { value: "PTA", label: "Patiala" },
    { value: "BVH", label: "Ballabhgrah" },
    { value: "AY", label: "Ayodhya" },
    { value: "AME", label: "Amethi" },
    { value: "CH", label: "Chandausi" },
    { value: "NBD", label: "Najibabad" },
    { value: "ABS", label: "Abhohar Jn" },
    { value: "SBB", label: "Sahibabad" },
    { value: "BGZ", label: "Bahdurgrah" },
    { value: "NNO", label: "Nangloi" },
    { value: "NUR", label: "Narela" },
    { value: "TKD", label: "Tughlakabad" },
    { value: "MDNR", label: "Modinagar" },
    { value: "NOLI", label: "Noli" },
    { value: "GNU", label: "Ganaur" },
    { value: "FDN", label: "Faridabad New Town" },
    { value: "PTRD", label: "Pataudi road" },
    { value: "BTU", label: "Braut" },
    { value: "AMRO", label: "Amroha" },
    { value: "PM", label: "Palam" },
    { value: "DSB", label: "Delhi sadar bazar" },
    { value: "JHS", label: "Jhansi" },
    { value: "MTJ", label: "Mathura" },
    { value: "AF", label: "Agra Fort" },
    { value: "ALJN", label: "Aligarh" },
    { value: "COI", label: "Chheoki" },
    { value: "MZP", label: "Mirzapur" },
    { value: "ETW", label: "Etawah" },
    { value: "TDL", label: "Tundala" },
    { value: "BNDA", label: "Banda" },
    { value: "MRA", label: "Morena" },
    { value: "LAR", label: "Lalitpur" },
    { value: "CKTD", label: "Chitrakut Dham" },
    { value: "MBA", label: "Mahoba" },
    { value: "FTP", label: "Fatehpur" },
    { value: "RKM", label: "Raja ki Mandi" },
    { value: "MKP", label: "Manikpur" },
    { value: "ORAI", label: "Orai" },
    { value: "KURJ", label: "Khajuraho" },
    { value: "PHD", label: "Phaphund" },
    { value: "DAA", label: "Datia" },
    { value: "DHO", label: "Dholpur Jn." },
    { value: "DBA", label: "Dabra" },
    { value: "DER", label: "Dadri" },
    { value: "KRJ", label: "Khurja" },
    { value: "GKP", label: "Gorakhpur Jn" },
    { value: "LJN", label: "Lucknow Jn" },
    { value: "CPR", label: "Chhapra Jn" },
    { value: "SV", label: "Siwan" },
    { value: "GD", label: "Gonda Jn" },
    { value: "MUV", label: "Manduwadih" },
    { value: "BST", label: "Basti" },
    { value: "AMH", label: "Azamgrah" },
    { value: "BUI", label: "Ballia" },
    { value: "MAU", label: "Mau Jn" },
    { value: "DEOS", label: "Deoria Sadar" },
    { value: "KGM", label: "Kathgodam" },
    { value: "KLD", label: "Khalilabad" },
    { value: "FBD", label: "Farrukhabad" },
    { value: "GCT", label: "Ghazipur City" },
    { value: "RUPC", label: "Rudrapur Ciry" },
    { value: "BLTR", label: "Betlthara Road" },
    { value: "BNZ", label: "Badshahnagar" },
    { value: "KSJ", label: "Kasganj Jn." },
    { value: "KJN", label: "Kannauj" },
    { value: "BCY", label: "Varanasi" },
    { value: "BTT", label: "Bhatni" },
    { value: "LKU", label: "Lalkuan Jn." },
    { value: "HDW", label: "Haldwani" },
    { value: "MUR", label: "Mankapur Jn." },
    { value: "KPV", label: "Kashipur" },
    { value: "PBE", label: "Pilibhit Jn." },
    { value: "BC", label: "Bareilly City" },
    { value: "GHY", label: "Guwahati" },
    { value: "NJP", label: "New Jalpaiguri" },
    { value: "KIR", label: "Katihar" },
    { value: "KYQ", label: "Kamakhya" },
    { value: "DMV", label: "Dimapur" },
    { value: "KNE", label: "Kishanganj" },
    { value: "NCB", label: "New Coochbehar" },
    { value: "NTSK", label: "New Tinsukia" },
    { value: "DBRT", label: "Dibrugarh Town" },
    { value: "NBQ", label: "New Bongaigaon" },
    { value: "RNY", label: "Rangiya Jn." },
    { value: "MXN", label: "Mariyani Jn." },
    { value: "NOQ", label: "New Alipurduar" },
    { value: "BOE", label: "Barsoi Jn." },
    { value: "DBRG", label: "Dibrugarh" },
    { value: "SCL", label: "Silchar" },
    { value: "JBN", label: "Jogbani" },
    { value: "LMG", label: "Lumding" },
    { value: "RGJ", label: "Raiganj" },
    { value: "BPRD", label: "Barpeta Road" },
    { value: "APDJ", label: "Alipurduar Jn." },
    { value: "DQG", label: "Dhupguri" },
    { value: "KOJ", label: "Kokrajhar" },
    { value: "SGUJ", label: "Siliguri Jn." },
    { value: "PRNA", label: "Purnea" },
    { value: "ARQ", label: "Araria Court" },
    { value: "BKN", label: "Bikaner" },
    { value: "ABR", label: "Abu Road" },
    { value: "RE", label: "Rewari" },
    { value: "AWR", label: "Alwar" },
    { value: "FA", label: "Falna" },
    { value: "SGNR", label: "Sri Ganga Nagar" },
    { value: "HSR", label: "Hisar" },
    { value: "JSM", label: "Jaisalmer" },
    { value: "BHL", label: "Bhilwara" },
    { value: "BKI", label: "Bandikui" },
    { value: "SOG", label: "Suratgarh" },
    { value: "NGO", label: "Nagaur" },
    { value: "MJ", label: "Marwar Jn." },
    { value: "PMY", label: "Pali Marwar" },
    { value: "BME", label: "Barmer" },
    { value: "BGKT", label: "Bhagar Ki Kothi" },
    { value: "LGH", label: "Lalgarh" },
    { value: "HMH", label: "Hanumangarh Jn." },
    { value: "BNW", label: "Bhiwani" },
    { value: "MTD", label: "Merta Road" },
    { value: "DO", label: "Dausa" },
    { value: "KSG", label: "Kishangarh" },
    { value: "FL", label: "Phulera" },
    { value: "DPA", label: "Durgapura" },
    { value: "BER", label: "Beawar" },
    { value: "SSA", label: "Sirsa" },
    { value: "MAS", label: "Chennai Central" },
    { value: "MS", label: "Chennai Egmore" },
    { value: "TBM", label: "Tambram" },
    { value: "CBE", label: "Coimbatore Jn." },
    { value: "TVC", label: "Tiruvananthapuram Central" },
    { value: "MDU", label: "Madurai Jn." },
    { value: "CLT", label: "Kozhikkode" },
    { value: "KPD", label: "Katpadi" },
    { value: "TCR", label: "Thrisur" },
    { value: "CGL", label: "Chengalpattu Jn." },
    { value: "AJJ", label: "Arakkonam Jn." },
    { value: "TRL", label: "Tiruvallur" },
    { value: "TPJ", label: "Tiruchchirappalli Jn" },
    { value: "TEN", label: "Tirunelveli Jn." },
    { value: "MAQ", label: "Mangalore Central" },
    { value: "ED", label: "Erode Jn" },
    { value: "SA", label: "Salem Jn." },
    { value: "CAN", label: "Kannur" },
    { value: "ERN", label: "Eraniel" },
    { value: "TUP", label: "Tiruppur" },
    { value: "AWY", label: "Aluva" },
    { value: "PGT", label: "Palakkad jn" },
    { value: "QLN", label: "Kollam Jn" },
    { value: "KTYM", label: "Kottayam" },
    { value: "SRR", label: "Shoranur Jn" },
    { value: "CNGR", label: "Chengannur" },
    { value: "NCJ", label: "Nagercoil Jn." },
    { value: "KYJ", label: "Kayankulam Jn" },
    { value: "TLY", label: "Thalassery" },
    { value: "TJ", label: "Thanjavur Jn" },
    { value: "MAJN", label: "Mangalore Jn" },
    { value: "DG", label: "Dindigul Jn" },
    { value: "RMM", label: "Rameswaram" },
    { value: "TN", label: "Tutikorin" },
    { value: "JTJ", label: "Jolarpattai" },
    { value: "TIR", label: "Tirur" },
    { value: "VM", label: "Villupuram Jn" },
    { value: "KCVL", label: "Kochuvalli" },
    { value: "ALLP", label: "Alppuzha" },
    { value: "PER", label: "Perambur" },
    { value: "MBM", label: "Mambalam" },
    { value: "GI", label: "Guduvancheri" },
    { value: "PRGL", label: "Perungalathur" },
    { value: "CAPE", label: "Kanniyakumari" },
    { value: "BDJ", label: "Vadakara" },
    { value: "KGQ", label: "kasargod" },
    { value: "TRVL", label: "Tiruvalla" },
    { value: "KMU", label: "kumbakonam" },
    { value: "PAY", label: "Payyannur" },
    { value: "CVP", label: "Kovilpatti" },
    { value: "VPT", label: "Virudhunagar Jn" },
    { value: "MV", label: "Mayiladuthurai Jn" },
    { value: "NGT", label: "Nagappattinam" },
    { value: "KZE", label: "Kanhangad" },
    { value: "KRR", label: "Karur Jn." },
    { value: "RMD", label: "Ramanathapuram" },
    { value: "KTU", label: "Kuttipuram" },
    { value: "MTP", label: "Mettupalaiyam" },
    { value: "CGY", label: "Changanacheri" },
    { value: "VAK", label: "Varkalashivagiri" },
    { value: "TRT", label: "Tiruttani" },
    { value: "SKL", label: "Singaperumalkoil" },
    { value: "AFK", label: "Angamali for Kaladi" },
    { value: "HYB", label: "Hyderabad" },
    { value: "KCG", label: "Kacheguda" },
    { value: "NED", label: "Huzur Saheb Nanded" },
    { value: "RJY", label: "Rajahmundry" },
    { value: "AWB", label: "Aurangabad" },
    { value: "RU", label: "Renigunta" },
    { value: "GNT", label: "Guntur" },
    { value: "WL", label: "Warangal" },
    { value: "SLO", label: "Samalkot" },
    { value: "KZJ", label: "Kazipet Jn" },
    { value: "OGL", label: "Ongole" },
    { value: "KMT", label: "Khammam" },
    { value: "GTL", label: "Guntakal" },
    { value: "GDR", label: "Gudur" },
    { value: "CCT", label: "Kakinada Tn." },
    { value: "RC", label: "Raichur" },
    { value: "PBN", label: "Parbhani" },
    { value: "NSL", label: "Nagarsol" },
    { value: "TEL", label: "Tenali" },
    { value: "ATP", label: "Anatpur" },
    { value: "NZB", label: "Nizamabad" },
    { value: "YG", label: "Yadgir" },
    { value: "EE", label: "Eluru" },
    { value: "BVRT", label: "Bhimavaram Tn." },
    { value: "HX", label: "Cuddapah" },
    { value: "LPI", label: "Lingampalli" },
    { value: "KRNT", label: "Kurnool Tn" },
    { value: "AKP", label: "Anakapalli" },
    { value: "J", label: "Jalna" },
    { value: "TDD", label: "Tadepalligudem" },
    { value: "CLX", label: "Chirala" },
    { value: "TUNI", label: "Tuni" },
    { value: "MCI", label: "Manchiryal" },
    { value: "BIDR", label: "Bidar" },
    { value: "AD", label: "Adoni" },
    { value: "COA", label: "Kakinada Port (new)" },
    { value: "RDM", label: "Ramagundam" },
    { value: "DMM", label: "Dharmavaram" },
    { value: "NS", label: "Narasapur" },
    { value: "BDCR", label: "Bhadrachalam Rd." },
    { value: "MALM", label: "Mantralayam Rd." },
    { value: "GDV", label: "Gudivada" },
    { value: "MABD", label: "Mahbubabad" },
    { value: "BMT", label: "Begumpet" },
    { value: "NDL", label: "Nandyal" },
    { value: "TDU", label: "Tandur" },
    { value: "CTO", label: "Chittoor" },
    { value: "VKB", label: "Vikarabad" },
    { value: "RAL", label: "Repalli" },
    { value: "TATA", label: "Tatanagar" },
    { value: "KGP", label: "Kharagpur" },
    { value: "ROU", label: "Rourkela" },
    { value: "HTE", label: "Hatia" },
    { value: "SHM", label: "Shalimar" },
    { value: "JSG", label: "Jharsuguda" },
    { value: "BKSC", label: "Bokaro Steel City" },
    { value: "BLS", label: "Balasore" },
    { value: "CKP", label: "Chakradharpur" },
    { value: "PRR", label: "Purulia Jn." },
    { value: "DGHA", label: "Digha" },
    { value: "BQA", label: "Bankura Jn." },
    { value: "MDN", label: "Midnapur" },
    { value: "ADRA", label: "Adra" },
    { value: "JGM", label: "Jhargram" },
    { value: "R", label: "Raipur" },
    { value: "BSP", label: "Bilaspur" },
    { value: "DURG", label: "Durg" },
    { value: "G", label: "Gondia" },
    { value: "RIG", label: "Raigharh" },
    { value: "CPH", label: "CPH" },
    { value: "APR", label: "Anuppur" },
    { value: "RJN", label: "Rajnandgaon" },
    { value: "SDL", label: "Shahdol" },
    { value: "BYT", label: "Bhatapara" },
    { value: "KRBA", label: "Korba" },
    { value: "BPHB", label: "Bhilai Power House" },
    { value: "ABKP", label: "Ambikapur" },
    { value: "ITR", label: "Itwari" },
    { value: "DGG", label: "Dongargadh" },
    { value: "MYS", label: "Mysore" },
    { value: "UBL", label: "Hubli Junction" },
    { value: "KJM", label: "Krishnarajapuram" },
    { value: "VSG", label: "Vasco-da-gama" },
    { value: "BAY", label: "Bellary Jn." },
    { value: "DVG", label: "Davangere" },
    { value: "BWT", label: "Bangarapet" },
    { value: "MYA", label: "Mandya" },
    { value: "HPT", label: "Hospet Jn." },
    { value: "KGI", label: "Kengeri" },
    { value: "BJP", label: "Bijapur" },
    { value: "SSPN", label: "Srisatyasaiprashanthinilayam" },
    { value: "SMET", label: "Shimoga Tn." },
    { value: "GDG", label: "Gadag Jn." },
    { value: "ASK", label: "Arsikere" },
    { value: "YNK", label: "Yelahanka" },
    { value: "HSRA", label: "Hosur" },
    { value: "TK", label: "Tumkur" },
    { value: "MLO", label: "Malur" },
    { value: "CPT", label: "Channapatna" },
    { value: "RMGM", label: "Ramanagaram" },
    { value: "WFD", label: "Whitefield" },
    { value: "NTW", label: "Nanjangud Tn" },
    { value: "KPN", label: "Kuppam" },
    { value: "BRC", label: "Vadodara Jn." },
    { value: "UJN", label: "Ujjain" },
    { value: "NVS", label: "Navsari" },
    { value: "RJT", label: "Rajkot" },
    { value: "VAPI", label: "Vapi" },
    { value: "RTM", label: "Ratlam" },
    { value: "JAM", label: "Jamnagar" },
    { value: "BH", label: "Bharuch Jn." },
    { value: "GIMB", label: "Gandhidham" },
    { value: "BHUJ", label: "Bhuj" },
    { value: "ANND", label: "Anand" },
    { value: "COR", label: "Chittorgarh" },
    { value: "AKV", label: "Ankleshwar" },
    { value: "ND", label: "Nadiad" },
    { value: "BIM", label: "Bilimora" },
    { value: "VRL", label: "Veraval" },
    { value: "BVC", label: "Bhavnagar" },
    { value: "DWK", label: "Dwarka" },
    { value: "DHD", label: "Dahod" },
    { value: "NAD", label: "Nagda" },
    { value: "SUNR", label: "Surendranagar" },
    { value: "DWX", label: "Dewas" },
    { value: "JND", label: "Junagarh" },
    { value: "WKR", label: "Wankaner" },
    { value: "VG", label: "Viramgam" },
    { value: "SIOB", label: "Samakhiali" },
    { value: "NMH", label: "Nimach" },
    { value: "KSB", label: "Kosamba" },
    { value: "MHD", label: "Mahemadabad & Kheda Road" },
    { value: "BTD", label: "Botad" },
    { value: "MYG", label: "Miyagam Karjan Jn." },
    { value: "UBR", label: "Umbergaon" },
    { value: "KIM", label: "Kim" },
    { value: "VR", label: "Virar" },
    { value: "BYR", label: "Bhayandar" },
    { value: "CCG", label: "Churchgate" },
    { value: "BSR", label: "Vasai Road" },
    { value: "NSP", label: "Nallasopara" },
    { value: "MDD", label: "Malad" },
    { value: "GMN", label: "Goregaon" },
    { value: "VTN", label: "Vaitarana" },
    { value: "KILE", label: "Kandivali" },
    { value: "VLP", label: "Vile Parley" },
    { value: "BOR", label: "Boisar" },
    { value: "MIRA", label: "Mira Road" },
    { value: "STC", label: "Santacruz" },
    { value: "JOS", label: "Jogeshwari" },
    { value: "PLG", label: "Palghar" },
    { value: "DIC", label: "Dahisar" },
    { value: "MM", label: "Mahim" },
    { value: "KHAR", label: "Khar Road" },
    { value: "GTR", label: "Grant Road" },
    { value: "DRD", label: "Dahanu Raod" },
    { value: "EPR", label: "Elphinstone Road" },
    { value: "CYR", label: "Charni Road" },
    { value: "JBP", label: "Jabalpur" },
    { value: "STA", label: "Satna" },
    { value: "KTE", label: "Katni" },
    { value: "REWA", label: "Rewa" },
    { value: "SWM", label: "Sawaimadhopur" },
    { value: "SGO", label: "Saugor" },
    { value: "BINA", label: "Bina" },
    { value: "BTE", label: "Bharatpur" },
    { value: "MYR", label: "Maihar" },
    { value: "DMO", label: "Damoh" },
    { value: "GUNA", label: "Guna" },
    { value: "PPI", label: "Pipariya" },
    { value: "GGC", label: "Gangapur City" },
    { value: "BHS", label: "Vidisha" },
    { value: "HBD", label: "Hoshangabad" },
    { value: "NU", label: "Narshinghpur" },
    { value: "HAN", label: "Hindaun City" },
    { value: "BAQ", label: "Ganjbasoda" },
    { value: "DKNT", label: "Dakaniya Talav" },
    { value: "PGMD", label: "Pragati Maidan" },
    { value: "DBSI", label: "Daya Basti" },
    { value: "KRTN", label: "Kirti Nagar" },
    { value: "NRVR", label: "Naraina Vihar" },
    { value: "DLPI", label: "Delhi Inderpuri" },
    { value: "BRSQ", label: "Brar Square" },
    { value: "SDPR", label: "Sardar Patel Marg" },
    { value: "SOJ", label: "Sarojini Nagar" },
    { value: "LDCY", label: "Lodhi Colony" },
    { value: "SWNR", label: "Sewa Nagar" },
    { value: "PZA", label: "PALAVANTANGAL" },
    { value: "AVD", label: "AVADI" },
    { value: "BZN", label: "BAGNAN" },
    { value: "PKU", label: "PANSKURA" },
    { value: "MCA", label: "MECHEDA" },
    { value: "VLCY", label: "Velachery" },
    { value: "PRGD", label: "Perungudi" },
    { value: "TRMN", label: "Taramani" },
    { value: "TYMR", label: "Thiruvanmiyur" },
    { value: "INDR", label: "Indira Nagar" },
    { value: "KTBR", label: "Kasturba Nagar" },
    { value: "KTPM", label: "Kotturpuram" },
    { value: "GWGR", label: "Greenways Road" },
    { value: "MNDY", label: "Mandaveli" },
    { value: "MTMY", label: "Thirumayilai" },
    { value: "MLHS", label: "Light House" },
    { value: "MTCN", label: "Thiruvallikeni" },
    { value: "MCPK", label: "Chepauk" },
    { value: "MCPT", label: "Chintadripet" },
    { value: "MPKT", label: "Chennai Park Town" },
    { value: "GDY", label: "Guindy" },
    { value: "SP", label: "Saidapet" },
    { value: "MKK", label: "Kodambakkam" },
    { value: "NBK", label: "Nungambakkam" },
    { value: "MSC", label: "Chetput" },
    { value: "PEW", label: "Perambur Loco Works" },
    { value: "PCW", label: "Perambur Carriage Works" },
    { value: "VJM", label: "Vyasarpadi Jeeva" },
    { value: "TNP", label: "Tondiarpet" },
    { value: "KOK", label: "Korukkupet" },
    { value: "MPK", label: "Chennai Park" },
    { value: "MSF", label: "Chennai Fort" },
    { value: "WST", label: "Washermanpet" },
    { value: "BBQ", label: "Basin Bridge" },
    { value: "RPM", label: "Royapuram" },
    { value: "MMCC", label: "Moore Market Complex" },
    { value: "MSB", label: "Chennai Beach" },
    { value: "SSP", label: "Santoshpur" },
    { value: "TLG", label: "Tollyganj" },
    { value: "BGJT", label: "Baghajatin" },
    { value: "BRJ", label: "Brace Bridge" },
    { value: "DDC", label: "Dum Dum Cant" },
    { value: "BLN", label: "Ballygunge" },
    { value: "DHK", label: "Dhakuria" },
    { value: "EDG", label: "Eden Garden" },
    { value: "BEQ", label: "Belur" },
    { value: "TPKR", label: "Tikiapara" },
    { value: "LLH", label: "Liluah" },
    { value: "BBT", label: "Birati" },
    { value: "MJT", label: "Majerhat" },
    { value: "KIRP", label: "Khidirpur" },
    { value: "PPGT", label: "Princep Ghat" },
    { value: "AGP", label: "Agarpara" },
    { value: "SRC", label: "Santragachi Junction" },
    { value: "VVH", label: "Vidyavihar" },
    { value: "TKNG", label: "Tilak Nagar" },
    { value: "SVE", label: "Sewri" },
    { value: "SNRD", label: "Sandhurst Road" },
    { value: "RRD", label: "Reay Road" },
    { value: "MRU", label: "Matunga Road" },
    { value: "MTN", label: "Matunga" },
    { value: "MEL", label: "Marine Lines" },
    { value: "MSD", label: "Bombay Masjid" },
    { value: "MX", label: "Mahalaxmi" },
    { value: "DKRD", label: "Dockyard Road" },
    { value: "CRD", label: "Currey Road" },
    { value: "CTGN", label: "Cotton Green" },
    { value: "CHF", label: "Chunabhatti" },
    { value: "CHG", label: "Chinchpokli" },
    { value: "BAP", label: "CBD Belapur" },
    { value: "VVB", label: "Viveka Vihar" },
    { value: "TKJ", label: "Tilak Bridge" },
    { value: "SZM", label: "Subji Mandi" },
    { value: "CSB", label: "Shivaji Bridge" },
    { value: "OKA", label: "Okhla" },
    { value: "MGP", label: "Mongolpuri" },
    { value: "DSJ", label: "Delhi Sadarjung" },
    { value: "DKZ", label: "Kishanganj" },
    { value: "BHD", label: "Badli" },
    { value: "GTNR", label: "Gomati Nagar" },
    { value: "RANI", label: "Rani" },
    { value: "MUT", label: "MEERUT CANTT." },
    { value: "JTTN", label: "Jorhat Town" },
    { value: "JUD", label: "Jagadhri" },
    { value: "GMO", label: "Gomoh Jn." },
    { value: "COB", label: "Coochbehar" },
    { value: "BNGN", label: "Bongaigaon" },
    { value: "BRD", label: "Bhandara Road" },
    { value: "UHL", label: "Una" },
    { value: "KPLH", label: "Kottipali" },
    { value: "ANSB", label: "Anandpur Sahib" },
    { value: "AO", label: "Aonla" },
    { value: "BRK", label: "Bahraich" },
    { value: "BTC", label: "Balaghat" },
    { value: "JDB", label: "Jagdalpur" },
    { value: "PNF", label: "Pangaon" },
    { value: "BJO", label: "Bijnor" },
    { value: "BSC", label: "Bulandshahar" },
    { value: "CUR", label: "Churu" },
    { value: "NAD", label: "Nagda" },
    { value: "DHI", label: "Dhule" },
    { value: "FTS", label: "Fatehpur Sikri" },
    { value: "KTW", label: "Kotdwara" },
    { value: "HRS", label: "Hathras" },
    { value: "JJN", label: "Jhunjhunu" },
    { value: "KGRA", label: "Kangra" },
    { value: "SRO", label: "Sirathu" },
    { value: "JONA", label: "Johna" },
    { value: "LMP", label: "Lakhimpur" },
    { value: "LLJ", label: "Lalganj" },
    { value: "MGZ", label: "Maharjganj" },
    { value: "JDNX", label: "Joginder Nagar" },
    { value: "MSTH", label: "Mibrik Tirath" },
    { value: "MLJ", label: "Mohanlal Ganj" },
    { value: "DMV", label: "Dimapur" },
    { value: "NDB", label: "Nandurbar" },
    { value: "NRT", label: "Narasaraopet" },
    { value: "NWD", label: "Nawada" },
    { value: "PTN", label: "Patan" },
    { value: "PBR", label: "Porbandar" },
    { value: "RBGJ", label: "Robertshabj" },
    { value: "SRE", label: "Saharanpur" },
    { value: "SML", label: "Shimla" },
    { value: "SIKR", label: "Sikar" },
    { value: "STP", label: "Sitapur" },
    { value: "TZTB", label: "Tezpur" },
    { value: "PQE", label: "Pawapuri" },
    { value: "CAPE", label: "Kanyakumari" },
  ];

  const options = trainList.map((train) => ({
    value: train.value,
    label: train.label,
  }));

  const handleChoose = (selectedOption) => {
    setSelectedTrain(
      selectedOption ? selectedOption.value + " " + selectedOption.label : null
    );
    onSelect(selectedOption.value + " " + selectedOption.label);
    // console.log(selectedOption ? selectedOption.label : null);
  };

  return (
    <div className="">
      <Select
        options={options}
        isClearable
        closeMenuOnSelect={true}
        components={animatedComponents}
        onChange={handleChoose}
        value={
          selectedTrain ? { value: selectedTrain, label: selectedTrain } : null
        }
      />
    </div>
  );
};

export default SelectTrain;
